version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "extincts-web-db"
      POSTGRES_USER: "extinct-user"
      POSTGRES_PASSWORD: "gfg"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./src/main/resources/db/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U extinct-user -d extincts-web-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - extincts-web-network
  extincts-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/extincts-web-db"
      SPRING_DATASOURCE_USERNAME: "extinct-user"
      SPRING_DATASOURCE_PASSWORD: "gfg"
    depends_on:
      - postgres
    networks:
      - extincts-web-network
volumes:
  postgres_volume:
networks:
  extincts-web-network:
    driver: bridge