services:
  extincts-web-backend:
    image: extincts:1.0-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extincts-web-backend
    ports:
      - "8181:8181"
    depends_on:
      - postgres-db
    environment:
      SERVER_PORT: 8181
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/extincts-web-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: extincts-web-db
      POSTGRES_USER: extinct-user
      POSTGRES_PASSWORD: gfg
    volumes:
      - postgres-db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres-db_volume:
