version: '3.8'
services:
  extincts-web:
    image: extincts:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8181
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/extincts-web-db
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: extincts-web-db
      POSTGRES_USER: extinct-user
      POSTGRES_PASSWORD: gfg
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./src/main/resources/db/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_volume:
