server:
  port: 8181

spring:
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER

token:
  signing:
    key: dc9086109fec08821a1e93528a25e6785d252db807a58b2d402d9cb5128efb84
    expiration: 86400000

storage:
  type: local
  local:
    directory: ./uploads
  base-url: http://localhost:8181/files/
  s3: # Реализация отсутствует
    bucket-name: your-bucket
    access-key: your-access-key
    secret-key: your-secret-key
    region: us-east-1

image:
  small_thumbnail:
    size: 150
  medium_thumbnail:
    size: 300
  large_thumbnail:
    size: 600

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  cors:
    enabled: true
  packagesToScan: com.warlock

logging:
  level:
    org:
      springdoc: DEBUG
      springframework:
        web:
          socket: DEBUG
          messaging: DEBUG