server:
  port: 8181

spring:
  profiles:
    active: test
  jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER

