INSERT INTO ROLES (NAME) VALUES ('user');
INSERT INTO ROLES (NAME) VALUES ('admin');
INSERT INTO STAND_CATEGORIES (NAME) VALUES ('Искусство');
INSERT INTO STAND_CATEGORIES (NAME) VALUES ('Технологии');
INSERT INTO STAND_CATEGORIES (NAME) VALUES ('Образование');
INSERT INTO STAND_CATEGORIES (NAME) VALUES ('Музыка');